/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ApitestImport } from './routes/apitest'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ApitestRoute = ApitestImport.update({
  id: '/apitest',
  path: '/apitest',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/apitest': {
      id: '/apitest'
      path: '/apitest'
      fullPath: '/apitest'
      preLoaderRoute: typeof ApitestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apitest': typeof ApitestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apitest': typeof ApitestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/apitest': typeof ApitestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apitest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apitest'
  id: '__root__' | '/' | '/apitest'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApitestRoute: typeof ApitestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApitestRoute: ApitestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apitest"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apitest": {
      "filePath": "apitest.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
